# **Continued Learning**
***

:::{.next_steps_box}
::::{.next_steps_box_header}
Common Next Steps
::::
::::{.inner_block}
Discuss common next steps for this type of an analysis in this box. Is there a specific number of steps that you need to do before a specific step? Is a "next step" more of an alternate step?
::::
:::

<!--
## Reinforcement Exercises

Uncomment this section if you're suggesting an exercise that reiterates a large portion of the case study so learners can practice a hard skill again, reinforcing topics from the case study
-->


## Advancement Exercises

Use this section to suggest different levels of exercises that build upon topics from the case study ... next steps, tangential skills, diving deeper into a side quest, etc.

Perhaps explain how the suggested exercises relate to the common next steps.

### Beginner

Bubble plot heatmap visualization

### Intermediate

Batch correction

#### Cluster to look for batch effects

#### Option A: Batch correct using knowledge of cell type (provided)

#### Option B: Batch correct without knowledge of cell type

### Advanced

#### Add cell type annotations

##### Option A: Azimuth

##### Option B: Clustering approach

##### Compare

#### Handle replicates

#### Plot Heatmaps

##### Heatmap A: no scaling

##### Heatmap B: scaling to allow for row-by-row comparisons

##### Heatmap C: Bubble plot to show number of cells with expression

Describe that Differential Gene Expression Analysis will be a common next step


<!--
Example from a previous case study: https://www.opencasestudies.org/ocs-bp-co2-emissions/#Suggested_Homework (though this example doesn't include different levels like Beginner, Intermediate, and Advanced)
-->

***
